// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrucksVistoria.Infrastructure;

#nullable disable

namespace TrucksVistoria.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260520214056_AdicionaEmpresaIdNoUsuario")]
    partial class AdicionaEmpresaIdNoUsuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("MobileTrucks")
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Clientes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clientes", "MobileTrucks");
                });

            modelBuilder.Entity("SeuProjeto.Models.ChecklistEntrada", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Ano")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ano");

                    b.Property<string>("AvariasCarroJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("avarias_carro_json");

                    b.Property<string>("ChecklistItensJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("checklist_itens_json");

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("cliente");

                    b.Property<string>("Combustivel")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("combustivel");

                    b.Property<string>("Cor")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cor");

                    b.Property<string>("CriadoPor")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("criado_por");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("Km")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("km");

                    b.Property<string>("Modelo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modelo");

                    b.Property<string>("NivelCombustivel")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("nivel_combustivel");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("placa");

                    b.Property<string>("Telefone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("telefone");

                    b.HasKey("Id");

                    b.ToTable("checklist_entrada", "MobileTrucks");
                });

            modelBuilder.Entity("TrucksVistoria.Domain.Entities.ChatMensagem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArquivoUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Entregue")
                        .HasColumnType("boolean");

                    b.Property<Guid>("RemetenteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SalaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Texto")
                        .HasColumnType("text");

                    b.Property<string>("TipoMidia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("Visualizado")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("SalaId");

                    b.ToTable("ChatMensagens", "MobileTrucks");
                });

            modelBuilder.Entity("TrucksVistoria.Domain.Entities.ChatParticipante", b =>
                {
                    b.Property<Guid>("SalaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataEntrada")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SalaId", "UsuarioId");

                    b.ToTable("ChatParticipantes", "MobileTrucks");
                });

            modelBuilder.Entity("TrucksVistoria.Domain.Entities.ChatSala", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("ChatSalas", "MobileTrucks");
                });

            modelBuilder.Entity("TrucksVistoria.Domain.Entities.ChatSugestao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<int>("FrequenciaUso")
                        .HasColumnType("integer");

                    b.Property<string>("TextoCompleto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TextoCurto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "TextoCurto")
                        .HasDatabaseName("IX_ChatSugestoes_Busca");

                    b.ToTable("ChatSugestoes", "MobileTrucks");
                });

            modelBuilder.Entity("TrucksVistoria.Domain.Entities.DashboardVistoria", b =>
                {
                    b.Property<string>("ClienteNome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataVistoria")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Equipe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FuncionarioEmail")
                        .HasColumnType("text");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UrlFoto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable((string)null);

                    b.ToView("dashboard_vistorias", "MobileTrucks");
                });

            modelBuilder.Entity("TrucksVistoria.Domain.Entities.Evidencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("UrlFoto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("VistoriaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VistoriaId");

                    b.ToTable("Evidencias", "MobileTrucks");
                });

            modelBuilder.Entity("TrucksVistoria.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Cargo");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("PasswordHash");

                    b.Property<string>("StatusPresenca")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", "MobileTrucks");
                });

            modelBuilder.Entity("TrucksVistoria.Domain.Entities.Veiculo", b =>
                {
                    b.Property<string>("Placa")
                        .HasColumnType("text");

                    b.Property<string>("ClienteNome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Placa");

                    b.ToTable("Veiculos", "MobileTrucks");
                });

            modelBuilder.Entity("TrucksVistoria.Domain.Entities.Vistoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClienteNome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ClienteNome");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Equipe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoServico")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("VeiculoPlaca")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("VeiculoPlaca");

                    b.ToTable("Vistorias", "MobileTrucks");
                });

            modelBuilder.Entity("TrucksVistoria.Domain.Entities.ChatMensagem", b =>
                {
                    b.HasOne("TrucksVistoria.Domain.Entities.ChatSala", "Sala")
                        .WithMany()
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("TrucksVistoria.Domain.Entities.ChatParticipante", b =>
                {
                    b.HasOne("TrucksVistoria.Domain.Entities.ChatSala", "Sala")
                        .WithMany()
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("TrucksVistoria.Domain.Entities.Evidencia", b =>
                {
                    b.HasOne("TrucksVistoria.Domain.Entities.Vistoria", null)
                        .WithMany("Evidencias")
                        .HasForeignKey("VistoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TrucksVistoria.Domain.Entities.Vistoria", b =>
                {
                    b.HasOne("TrucksVistoria.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrucksVistoria.Domain.Entities.Veiculo", null)
                        .WithMany("Vistorias")
                        .HasForeignKey("VeiculoPlaca");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TrucksVistoria.Domain.Entities.Veiculo", b =>
                {
                    b.Navigation("Vistorias");
                });

            modelBuilder.Entity("TrucksVistoria.Domain.Entities.Vistoria", b =>
                {
                    b.Navigation("Evidencias");
                });
#pragma warning restore 612, 618
        }
    }
}
