// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrucksVistoria.Infrastructure;

#nullable disable

namespace TrucksVistoria.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("MobileTrucks")
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TrucksVistoria.Domain.Entities.DashboardVistoria", b =>
                {
                    b.Property<string>("ClienteNome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataVistoria")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Equipe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UrlFoto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable((string)null);

                    b.ToView("dashboard_vistorias", "MobileTrucks");
                });

            modelBuilder.Entity("TrucksVistoria.Domain.Entities.Evidencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("UrlFoto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("VistoriaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VistoriaId");

                    b.ToTable("Evidencias", "MobileTrucks");
                });

            modelBuilder.Entity("TrucksVistoria.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", "MobileTrucks");
                });

            modelBuilder.Entity("TrucksVistoria.Domain.Entities.Veiculo", b =>
                {
                    b.Property<string>("Placa")
                        .HasColumnType("text");

                    b.Property<string>("ClienteNome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Placa");

                    b.ToTable("Veiculos", "MobileTrucks");
                });

            modelBuilder.Entity("TrucksVistoria.Domain.Entities.Vistoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Equipe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoServico")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("VeiculoPlaca")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("VeiculoPlaca");

                    b.ToTable("Vistorias", "MobileTrucks");
                });

            modelBuilder.Entity("TrucksVistoria.Domain.Entities.Evidencia", b =>
                {
                    b.HasOne("TrucksVistoria.Domain.Entities.Vistoria", null)
                        .WithMany("Evidencias")
                        .HasForeignKey("VistoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TrucksVistoria.Domain.Entities.Vistoria", b =>
                {
                    b.HasOne("TrucksVistoria.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrucksVistoria.Domain.Entities.Veiculo", null)
                        .WithMany("Vistorias")
                        .HasForeignKey("VeiculoPlaca");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TrucksVistoria.Domain.Entities.Veiculo", b =>
                {
                    b.Navigation("Vistorias");
                });

            modelBuilder.Entity("TrucksVistoria.Domain.Entities.Vistoria", b =>
                {
                    b.Navigation("Evidencias");
                });
#pragma warning restore 612, 618
        }
    }
}
